### PR TITLE
Fix some strings in the Hebrew translation

### PR DESCRIPTION
**Pull request by ItielMaN**
This is not the final version of the file, a question first:
Can I translate "batch" as something like "multiple programs" (or "multiple entries", when applicable)?

### CODE REVIEW

**Comment by tomkoen** [comment]
Merged, thanks

**Comment by ItielMaN** [comment]
You seem to have missed the question in the first comment here :(

**Comment by kleuter** [comment]
> Can I translate "batch" as something like "multiple programs" (or "multiple entries", when applicable)?
sure!

**Comment by tomkoen** [comment]
> Can I translate "batch" as something like "multiple programs" (or "multiple entries", when applicable)?

sure!

**Pull request merged**
